#!/bin/bash

script/branding

if [ ! -d "sass-spec" ]; then
  git clone --branch feature/output-styles https://github.com/mgreter/sass-spec.git
fi
if [ ! -d "sassc" ]; then
  git clone https://github.com/sass/sassc.git
fi
