#!/bin/bash
if [ "x$COVERAGE" == "xyes" ]; then
  pip2 install --user gcovr
  pip2 install --user cpp-coveralls
else
  echo "no dependencies to install"
fi

case $TOOLING in
  autotools)
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo add-apt-repository -y ppa:rbose-debianizer/automake &> /dev/null
      sudo apt-get -qq update
      sudo apt-get -qq install automake
    fi
  ;;
  meson)
    pip3 install meson ninja
esac

exit 0
