#!/bin/bash

set -e

script/bootstrap

# Scaffold build system
cmake --build .

# Run the test suite
ctest --verbose

if ["$BUILD_DOCUMENTATION" == "true"]; then
  cmake --build . --target documentation
fi
