// Hampton Catlin. Copyright (C) 2012. MIT
#ifndef HEADER_SRC_LIBINFO_H_INCLUDED
#define HEADER_SRC_LIBINFO_H_INCLUDED

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "libraryinfo.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */

#cmakedefine LIBRARY_NAME               "@LIBRARY_NAME@"
#cmakedefine LIBRARY_CODENAME           "@LIBRARY_CODENAME@"
#cmakedefine LIBRARY_COPYRIGHT_YEARS    "@LIBRARY_COPYRIGHT_YEARS@"
#cmakedefine LIBRARY_VERSION_MAJOR      @LIBRARY_VERSION_MAJOR@
#cmakedefine LIBRARY_VERSION_MINOR      @LIBRARY_VERSION_MINOR@
#cmakedefine LIBRARY_VERSION_PATCH      @LIBRARY_VERSION_PATCH@
#cmakedefine LIBRARY_VERSION_TYPE       "@LIBRARY_VERSION_TYPE@"
#cmakedefine LIBRARY_VERSION_STRING     "@LIBRARY_VERSION_STRING@"
#cmakedefine LIBRARY_VENDOR_ID          "@LIBRARY_VENDOR_ID@"
#cmakedefine LIBRARY_VENDOR_NAME        "@LIBRARY_VENDOR_NAME@"
#cmakedefine LIBRARY_VENDOR_URL         "@LIBRARY_VENDOR_URL@"
#cmakedefine LIBRARY_ID                 "@LIBRARY_VENDOR_ID@"

#ifndef LIBRARY_NAME
#   error "Please specify the library name in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_CODENAME
#   error "Please specify the library codename in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_COPYRIGHT_YEARS
#   error "Please specify the library copyright years (years during which this library was created, edited, or modified) in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_VERSION_MAJOR
#   define LIBRARY_VERSION_MAJOR 0
#endif

#ifndef LIBRARY_VERSION_MINOR
#   define LIBRARY_VERSION_MINOR 0
#endif

#ifndef LIBRARY_VERSION_PATCH
#   define LIBRARY_VERSION_PATCH 0
#endif

#ifndef LIBRARY_VERSION_TYPE
#   define LIBRARY_VERSION_TYPE "SNAPSHOT"
#endif

#ifndef LIBRARY_VERSION_STRING
#   define LIBRARY_VERSION_STRING LIBRARY_VERSION_MAJOR "." LIBRARY_VERSION_MINOR "." LIBRARY_VERSION_PATCH "-" LIBRARY_VERSION_TYPE
#endif

#ifndef LIBRARY_VENDOR_ID
#   error "Please specify the library vendor id in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_VENDOR_NAME
#   error "Please specify the library vendor name in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_VENDOR_URL
#   error "Please specify the library vendor URL in the top-level CMakeLists.txt file."
#endif

#ifndef LIBRARY_ID
#   define LIBRARY_ID LIBRARY_VENDOR_ID "." LIBRARY_CODENAME
#endif

#endif
